FROM node:lts

RUN npm config set @nuxeo:registry=https://packages.nuxeo.com/repository/npm-public-archives/

WORKDIR /ui

# Copy packages
COPY packages ./packages

# Copy package.json and install dependencies
COPY package*.json ./

RUN npm install

# Copy application source code
COPY . .

EXPOSE 5000

CMD ["npm", "start"]
